/*
    Memory
    $A000-$BFFF (BASIC ROM 8K) 
    $D000-$DFFF (CHAR ROM - IO 4K)
    $E000-$FFFF (KERNAL ROM 8K)
*/
.const ALL_RAM_VISIBLE = %00             // (2O KB)
.const DISABLED_BASIC_AND_KERNAL = %01   // ENABLED CHAR/IO (16 KB)
.const ENABLED_BASIC_AND_KERNAL = %11    // default - ENABLED BASIC/KERNAL/CHAR-IO (0 KB)

.const CHAR_ROM_VISIBLE = %000           // EXCEPT for ALL_RAM_VISIBLE
.const IO_AREA_VISIBLE = %100            // default - EXCEPT for ALL_RAM_VISIBLE

.const CONFIGURED_MEMORY = DISABLED_BASIC_AND_KERNAL | IO_AREA_VISIBLE 